# Generated by Django 4.0.5 on 2022-10-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Publication', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=400)),
                ('pub_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('img', models.CharField(max_length=50)),
            ],
        ),
    ]
