# Generated by Django 4.0.5 on 2022-10-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='img',
            field=models.ImageField(upload_to='...static/img'),
        ),
    ]
