# Generated by Django 4.0.5 on 2022-10-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_books_category_alter_books_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('contact', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='Author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='Publication',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='img',
            field=models.ImageField(upload_to='store/images'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
